baseURL: 'https://sheb.me/'
languageCode: 'en-us'
title: "Sheb's Blog"
theme: "PaperMod"

paginate: 5
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Posts
          url: archives
          weight: 5
        - name: Search
          url: search
          weight: 10
        - name: Tags
          url: tags
          weight: 10
        - name: About
          url: about

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Mike Sheb's Personal Blog"
  author: Mike
  keywords: [ Blog, Portfolio ]
  defaultTheme: "light"
  disableThemeToggle: false
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  # comments: false

  images: [ "papermod-cover.png" ]

  profileMode:
    enabled: true
    title: Mike Sheb
    subtitle: "Software Engineer. Go, Rust, Elixir, FPGA"
    imageUrl: "/avatar.jpg"
    imageTitle: Mike's Avatar
    imageWidth: 320
    imageHeight: 320
    buttons:
      - name: Posts
        url: archives
      - name: Tags
        url: tags
      - name: CV
        url: cv.pdf

  homeInfoParams:
    Title: "PaperMod"
    Content: >
  

  socialIcons:
    - name: github
      url: "https://github.com/sheb-gregor"
    - name: twitter
      url: "https://twitter.com/sheb_m"
    - name: CV
      url: "cv.pdf"
    - name: Rss
      url: "index.xml"

  editPost:
    URL: "https://github.com/sheb-gregor/blog"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  assets:
    disableHLJS: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    lineNos: true
    style: base16-snazzy
#    noClasses: false
#  highlight:
#    anchorLineNos: false
#    codeFences: true
#    guessSyntax: false
#    hl_Lines: ""
#    hl_inline: false
#    lineAnchors: ""
#    lineNoStart: 1
#    lineNos: false
#    lineNumbersInTable: true
#    noClasses: true
#    noHl: false
#    style: base16-snazzy
#    tabWidth: 4

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
